import QRCode from 'qrcode';
import { dollarsToCents, cashAppLink, lightningAddress, lnurlEncode, centsToMillisats, fetchRate, requestInvoice } from './payments.js';

const form = document.querySelector('#tip-form');
const methodInputs = document.querySelectorAll('input[name="method"]');
const handle = document.querySelector('#handle');
const handleLabel = document.querySelector('#handle-label');
const handleHint = document.querySelector('#handle-hint');
const result = document.querySelector('#result');
const button = document.querySelector('#generate');
const error = document.querySelector('#error');
let generation = 0;

function selectedMethod() { return document.querySelector('input[name="method"]:checked').value; }
function money(cents) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100); }
function node(tag, className, text) {
  const element = document.createElement(tag);
  if (className) element.className = className;
  element.textContent = text;
  return element;
}
function updateMethod() {
  const lightning = selectedMethod() === 'lightning';
  handleLabel.textContent = lightning ? 'Customer’s Lightning address' : 'Customer’s $cashtag';
  handle.placeholder = lightning ? 'name@domain.com' : '$customer';
  handleHint.textContent = lightning ? 'Their wallet must support Lightning Address (LNURL-pay).' : 'The customer receives the tip at this Cash App profile.';
  handle.value = '';
  result.hidden = true;
  error.hidden = true;
  generation++;
}
methodInputs.forEach(input => input.addEventListener('change', updateMethod));

async function showResult({ title, subtitle, payload, amount, note, link, label, details, warning }, current) {
  const invoiceQr = payload.startsWith('lightning:');
  const qr = await QRCode.toString(payload, { type: 'svg', margin: 4, width: invoiceQr ? 400 : 256, errorCorrectionLevel: invoiceQr ? 'L' : 'M', color: { dark: '#132626', light: '#ffffff' } });
  if (current !== generation) return;
  result.replaceChildren();
  const top = node('div', 'result-top', 'READY TO TIP');
  const heading = node('h2', '', title);
  const sub = node('p', 'result-sub', subtitle);
  const qrBox = node('div', invoiceQr ? 'qr-box invoice-qr' : 'qr-box', '');
  qrBox.innerHTML = qr; // SVG is generated by the QR library, never sourced from the recipient.
  qrBox.querySelector('svg')?.setAttribute('aria-label', 'Payment QR code');
  const amountLabel = node('strong', 'result-amount', amount);
  const detail = node('p', 'result-detail', details);
  const caution = node('p', warning ? 'notice warning' : 'notice', note);
  result.append(top, heading, sub, qrBox, amountLabel, detail, caution);
  const actions = node('div', 'result-actions', '');
  if (link) {
    const anchor = node('a', 'action primary', label);
    anchor.href = link;
    anchor.target = '_blank';
    anchor.rel = 'noopener noreferrer';
    actions.append(anchor);
  }
  const copy = node('button', 'action secondary', 'Copy payment details');
  copy.type = 'button';
  copy.addEventListener('click', async () => {
    try { await navigator.clipboard.writeText(payload); copy.textContent = 'Copied!'; }
    catch { copy.textContent = 'Copy unavailable — scan the QR'; }
  });
  actions.append(copy);
  result.append(actions);
  result.hidden = false;
  result.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

form.addEventListener('submit', async event => {
  event.preventDefault();
  const current = ++generation;
  result.hidden = true;
  error.hidden = true;
  button.disabled = true;
  button.textContent = 'Preparing your QR…';
  try {
    const cents = dollarsToCents(document.querySelector('#amount').value);
    const amount = money(cents);
    if (selectedMethod() === 'cash') {
      const cash = cashAppLink(handle.value);
      await showResult({ title: 'Send with Cash App', subtitle: `Tip for ${cash.handle}`, payload: cash.url, amount,
        details: 'Scan to open the customer’s Cash App profile.',
        note: 'Cash App’s public $cashtag link does not guarantee a prefilled amount. Enter the amount shown above in Cash App and verify the recipient before sending.',
        link: cash.url, label: 'Open Cash App', warning: false }, current);
    } else {
      const address = lightningAddress(handle.value);
      let rate, msats, invoice, failure;
      try {
        rate = await fetchRate();
        msats = centsToMillisats(cents, rate);
        invoice = await requestInvoice(address, msats);
      } catch (cause) {
        if (/outside this recipient’s Lightning limits|invoice amount does not match/.test(cause.message)) throw cause;
        failure = cause;
      }
      if (current !== generation) return;
      if (invoice) {
        await showResult({ title: 'Pay with Lightning', subtitle: `Invoice for ${address.address}`, payload: `lightning:${invoice}`, amount,
          details: `Requested ${Math.round(msats / 1000).toLocaleString()} sats · Live rate $${rate.toLocaleString('en-US')} / BTC`,
          note: 'Invoice amount was checked against the requested amount. Verify the recipient and amount in your wallet before paying. Invoices expire; generate a new one if needed.',
          link: `lightning:${invoice}`, label: 'Open Lightning wallet', warning: false }, current);
      } else {
        const lnurl = lnurlEncode(address.url);
        await showResult({ title: 'Pay with Lightning', subtitle: `Lightning Address for ${address.address}`, payload: lnurl, amount,
          details: msats ? `Suggested amount: ${Math.round(msats / 1000).toLocaleString()} sats (live rate $${rate.toLocaleString('en-US')} / BTC)` : 'No live BTC/USD quote available.',
          note: `Could not generate an invoice in this browser (${failure?.message || 'network/CORS error'}). Scan the LNURL-pay QR with a compatible wallet; the wallet requests the invoice. Enter the displayed tip amount yourself and verify it before paying.`,
          link: null, warning: true }, current);
      }
    }
  } catch (cause) {
    if (current === generation) { error.textContent = cause.message || 'Something went wrong. Try again.'; error.hidden = false; }
  } finally {
    if (current === generation) { button.disabled = false; button.textContent = 'Generate payment QR'; }
  }
});
